require_relative '../book'
require_relative '../student'
require_relative '../classroom'
require_relative '../teacher'
require_relative '../person'
require_relative '../rental'
require_relative '../capitalize_decolator'
require_relative '../trim_decolator'
